spring.application.name=springboot-rest-api-poc

#DATABASE CONNECTION
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#H2 DEVELOPMENT TOOL
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Actuators
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always